### ISSUE TITLE
Add footers

### ISSUE THREAD

**Issue by mturkson23** [codemeleon/african_microbiome_portal#4]
Add footers to website layout

**Comment by mturkson23** [comment]
Pushed https://github.com/codemeleon/Database/commit/99be41b9043db2ebec9e8b6741ec40103ea235c6 with changes to mainLayout.html

Still struggling to let the footer lay on the bottom. Might have to touch some other files but I am avoiding doing that.

**Comment by codemeleon** [comment]
It is done
